name: homeassistant-dev

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant-dev
    restart: unless-stopped
    ports:
      - "8123:8123"
    environment:
      TZ: Europe/Moscow
    volumes:
      - ./data:/config
      - ./custom_components:/config/custom_components
